import Head from 'next/head'

export default function LegalPage() {
  return (
    <>
      <Head>
        <title>Legal | Vote4GOAT</title>
        <meta name="robots" content="noindex" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="min-h-screen bg-background px-4 py-12 text-white font-sans">
        <div className="max-w-2xl mx-auto">

          <div className="mb-8">
            <a href="/" className="text-2xl font-bold text-white">Vote4<span className="text-goat">GOAT</span></a>
            <p className="text-xs text-white/30 mt-1 uppercase tracking-widest">Legal</p>
          </div>

          <nav className="flex gap-3 mb-10 flex-wrap">
            <a href="#terms" className="text-xs px-3 py-1.5 rounded-full border border-goat/40 text-goat hover:bg-goat/10 transition">Terms and Conditions</a>
            <a href="#privacy" className="text-xs px-3 py-1.5 rounded-full border border-white/10 text-white/50 hover:border-white/20 hover:text-white/70 transition">Privacy Policy</a>
            <a href="#cookies" className="text-xs px-3 py-1.5 rounded-full border border-white/10 text-white/50 hover:border-white/20 hover:text-white/70 transition">Cookie Policy</a>
          </nav>

          <section id="terms" className="mb-16 scroll-mt-8">
            <h1 className="text-xl font-bold text-goat mb-1">Terms and Conditions</h1>
            <p className="text-xs text-white/30 mb-8">Last updated: March 2026</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">1. Who we are</h2>
            <p className="text-sm text-white/50 mb-4">Vote4GOAT is operated by Vote4GOAT, an individual-run project based in Spain. Contact: <a href="mailto:hello@vote4goat.com" className="text-goat hover:underline">hello@vote4goat.com</a>. The Platform is accessible at vote4goat.com and allows users to vote, rank and debate about athletes and other public figures across sports and other categories.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">2. Acceptance of terms</h2>
            <p className="text-sm text-white/50 mb-4">By accessing or using Vote4GOAT, you agree to be bound by these Terms and Conditions. We reserve the right to update these terms at any time. Continued use of the Platform after changes constitutes acceptance of the updated terms.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">3. Who can use Vote4GOAT</h2>
            <p className="text-sm text-white/50 mb-4">Vote4GOAT is intended for users aged 13 and over. Users under 16 in the EU must have parental consent in accordance with GDPR Article 8.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">4. User accounts</h2>
            <p className="text-sm text-white/50 mb-4">You may use certain features without registering. When creating an account, you agree to provide accurate information, keep your credentials confidential, and notify us of any unauthorized use. We reserve the right to suspend accounts that violate these terms or engage in fraudulent activity including vote manipulation.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">5. Acceptable use</h2>
            <p className="text-sm text-white/50 mb-4">You agree not to manipulate voting results through bots or coordinated inauthentic behavior, harass or harm other users, post unlawful or defamatory content, attempt unauthorized access to any part of the Platform, or scrape or redistribute Platform data without permission.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">6. Intellectual property</h2>
            <p className="text-sm text-white/50 mb-4">All content on Vote4GOAT including design, code, logos, mode names (DVELS, T0PS, R4NK, LINEUP), and ranking data is the property of the Platform operator. Player names are referenced for informational and entertainment purposes only. Vote4GOAT is not affiliated with any athlete or sports organization.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">7. Voting integrity</h2>
            <p className="text-sm text-white/50 mb-2">Rankings are generated by real user votes. We use IP-based rate limiting and device fingerprinting to detect and filter fraudulent votes.</p>
            <div className="bg-white/5 border-l-2 border-goat px-4 py-3 rounded-r-xl mb-4">
              <p className="text-sm text-white/60">Vote4GOAT rankings represent the collective opinion of its users and do not constitute official rankings endorsed by any sports body.</p>
            </div>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">8. Limitation of liability</h2>
            <p className="text-sm text-white/50 mb-4">The Platform is provided as is without warranties. To the maximum extent permitted by law, we are not liable for any indirect or consequential damages arising from your use of the Platform.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">9. Governing law</h2>
            <p className="text-sm text-white/50 mb-4">These Terms are governed by the laws of Spain. Any disputes shall be subject to the exclusive jurisdiction of the courts of Spain.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">10. Contact</h2>
            <p className="text-sm text-white/50"><a href="mailto:hello@vote4goat.com" className="text-goat hover:underline">hello@vote4goat.com</a></p>
          </section>

          <div className="h-px bg-white/5 mb-16" />

          <section id="privacy" className="mb-16 scroll-mt-8">
            <h1 className="text-xl font-bold text-goat mb-1">Privacy Policy</h1>
            <p className="text-xs text-white/30 mb-8">Last updated: March 2026 · Compliant with GDPR (EU 2016/679) and Spanish LOPDGDD</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">1. Data controller</h2>
            <p className="text-sm text-white/50 mb-4">Vote4GOAT, operated by an individual based in Spain. Contact: <a href="mailto:hello@vote4goat.com" className="text-goat hover:underline">hello@vote4goat.com</a></p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">2. What data we collect</h2>
            <p className="text-sm font-medium text-white/70 mb-1">Data you provide directly</p>
            <p className="text-sm text-white/50 mb-4">Email address (required for registration), username (required, displayed publicly), year of birth (optional), country (optional), profile photo (optional).</p>
            <p className="text-sm font-medium text-white/70 mb-1">Data collected automatically</p>
            <p className="text-sm text-white/50 mb-4">IP address (collected with each vote for fraud prevention), device fingerprint (browser and device characteristics, used exclusively for vote integrity), voting history (associated with your account or IP), usage data (pages visited, time on site).</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">3. Legal basis for processing</h2>
            <p className="text-sm text-white/50 mb-4">Contract performance (Art. 6.1.b GDPR) for email and username. Legitimate interest (Art. 6.1.f GDPR) for IP addresses and device fingerprints. Consent (Art. 6.1.a GDPR) for optional data such as year of birth, country, and analytics cookies.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">4. How we use your data</h2>
            <p className="text-sm text-white/50 mb-4">To provide and improve the service, detect and prevent fraudulent voting, generate personalized ranking insights, send service-related communications, and analyze platform usage.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">5. Data retention</h2>
            <p className="text-sm text-white/50 mb-4">Account data until you delete your account. Voting history retained indefinitely as part of the ranking system, anonymized after account deletion. IP addresses for 12 months. Analytics data for 26 months.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">6. Data sharing</h2>
            <p className="text-sm text-white/50 mb-4">We do not sell your data. We share only with Supabase (database, EU data centers), Vercel (hosting), and analytics providers if you consent. All processors comply with GDPR.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">7. Your rights</h2>
            <p className="text-sm text-white/50 mb-4">Under GDPR you have the right to access, rectify, erase, port, and object to processing of your data, and to withdraw consent at any time. Contact <a href="mailto:hello@vote4goat.com" className="text-goat hover:underline">hello@vote4goat.com</a>. You may also complain to the AEPD at <a href="https://www.aepd.es" target="_blank" rel="noopener noreferrer" className="text-goat hover:underline">aepd.es</a>.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">8. Data security</h2>
            <p className="text-sm text-white/50 mb-4">We use HTTPS, access controls, and regular security reviews. No system is completely secure.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">9. Children</h2>
            <p className="text-sm text-white/50 mb-4">Vote4GOAT is not directed at children under 13. Contact us to delete any data provided by a child.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">10. Changes</h2>
            <p className="text-sm text-white/50">We will notify registered users of significant changes by email.</p>
          </section>

          <div className="h-px bg-white/5 mb-16" />

          <section id="cookies" className="mb-16 scroll-mt-8">
            <h1 className="text-xl font-bold text-goat mb-1">Cookie Policy</h1>
            <p className="text-xs text-white/30 mb-8">Last updated: March 2026</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">1. What are cookies</h2>
            <p className="text-sm text-white/50 mb-4">Cookies are small text files stored on your device that help the website remember information about your visit.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">2. Cookies we use</h2>
            <p className="text-sm font-medium text-white/70 mb-1">Essential (no consent required)</p>
            <p className="text-sm text-white/50 mb-4">Session cookie (expires when you close browser), authentication token from Supabase (expires after 7 days), cookie consent preference (expires after 12 months).</p>
            <p className="text-sm font-medium text-white/70 mb-1">Analytics (consent required)</p>
            <p className="text-sm text-white/50 mb-4">Vercel Analytics collects anonymized usage data. No personally identifiable information. Retained 26 months.</p>
            <p className="text-sm font-medium text-white/70 mb-1">Fraud prevention (legitimate interest)</p>
            <p className="text-sm text-white/50 mb-4">Device fingerprinting to prevent vote manipulation. Does not use cookies but serves a similar purpose.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">3. Managing cookies</h2>
            <p className="text-sm text-white/50 mb-4">You can control cookies through your browser settings. Disabling essential cookies will affect certain features.</p>

            <h2 className="text-sm font-semibold text-white mt-6 mb-2">4. Contact</h2>
            <p className="text-sm text-white/50"><a href="mailto:hello@vote4goat.com" className="text-goat hover:underline">hello@vote4goat.com</a></p>
          </section>

          <div className="h-px bg-white/5 mb-8" />
          <p className="text-xs text-white/20 text-center mb-8">vote4goat.com · Based in Spain · All rights reserved</p>

        </div>
      </main>
    </>
  )
}
